apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  selector:
    matchLabels:
      app: customer-service-pod
  template:
    metadata:
      labels:
        app: customer-service-pod
    spec:
      containers:
      - name: customer-service-container
        image: customer-service:local
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80


