apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      component: service-auth
  template:
    metadata:
      labels:
        component: service-auth
    spec:
      containers:
        - env:
            - name: SPRING_EUREKA
              value: http://eureka-cluster-ip-service:8761/eureka
          image: asia.gcr.io/citric-tiger-271310/service-auth:1.17.5
          name: service-auth
          ports:
            - containerPort: 80
